<?php
/**
 * PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRITest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com.cryptoapis.rest_apis.sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2023-04-25
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace com.cryptoapis.rest_apis.sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRITest Class Doc Comment
 *
 * @category    Class
 * @description PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRI
 * @package     com.cryptoapis.rest_apis.sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRITest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRI"
     */
    public function testPrepareATransactionFromAnAddressInHDWalletXPubYPubZPubRI()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sig_hash"
     */
    public function testPropertySigHash()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blockchain_specific"
     */
    public function testPropertyBlockchainSpecific()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
