<?php
/**
 * CreateSubscriptionsForApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  com.cryptoapis.rest_apis.sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2023-04-25
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.cryptoapis.rest_apis.sdk\Test\Api;

use \com.cryptoapis.rest_apis.sdk\Configuration;
use \com.cryptoapis.rest_apis.sdk\ApiException;
use \com.cryptoapis.rest_apis.sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CreateSubscriptionsForApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.cryptoapis.rest_apis.sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CreateSubscriptionsForApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for blockHeightReached
     *
     * Block Height Reached.
     *
     */
    public function testBlockHeightReached()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for minedTransaction
     *
     * Mined Transaction.
     *
     */
    public function testMinedTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newBlock
     *
     * New Block.
     *
     */
    public function testNewBlock()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newConfirmedCoinsTransactions
     *
     * New Confirmed Coins Transactions.
     *
     */
    public function testNewConfirmedCoinsTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newConfirmedCoinsTransactionsAndEachConfirmation
     *
     * New Confirmed Coins Transactions And Each Confirmation.
     *
     */
    public function testNewConfirmedCoinsTransactionsAndEachConfirmation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newConfirmedInternalTransactions
     *
     * New Confirmed Internal Transactions.
     *
     */
    public function testNewConfirmedInternalTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newConfirmedInternalTransactionsAndEachConfirmation
     *
     * New Confirmed Internal Transactions And Each Confirmation.
     *
     */
    public function testNewConfirmedInternalTransactionsAndEachConfirmation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newConfirmedTokensTransactions
     *
     * New Confirmed Tokens Transactions.
     *
     */
    public function testNewConfirmedTokensTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newConfirmedTokensTransactionsAndEachConfirmation
     *
     * New Confirmed Tokens Transactions And Each Confirmation.
     *
     */
    public function testNewConfirmedTokensTransactionsAndEachConfirmation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newRevertedBlock
     *
     * New Reverted Block.
     *
     */
    public function testNewRevertedBlock()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newUnconfirmedCoinsTransactions
     *
     * New Unconfirmed Coins Transactions.
     *
     */
    public function testNewUnconfirmedCoinsTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for newUnconfirmedTokensTransactions
     *
     * New Unconfirmed Tokens Transactions.
     *
     */
    public function testNewUnconfirmedTokensTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
