<?php
/**
 * HDWalletsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  com.cryptoapis.rest_apis.sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2023-04-25
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.cryptoapis.rest_apis.sdk\Test\Api;

use \com.cryptoapis.rest_apis.sdk\Configuration;
use \com.cryptoapis.rest_apis.sdk\ApiException;
use \com.cryptoapis.rest_apis.sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HDWalletsApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.cryptoapis.rest_apis.sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HDWalletsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deriveAndSyncNewChangeAddresses
     *
     * Derive And Sync New Change Addresses.
     *
     */
    public function testDeriveAndSyncNewChangeAddresses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deriveAndSyncNewReceivingAddresses
     *
     * Derive And Sync New Receiving Addresses.
     *
     */
    public function testDeriveAndSyncNewReceivingAddresses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHDWalletXPubYPubZPubAssets
     *
     * Get HD Wallet (xPub, yPub, zPub) Assets.
     *
     */
    public function testGetHDWalletXPubYPubZPubAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getHDWalletXPubYPubZPubDetails
     *
     * Get HD Wallet (xPub, yPub, zPub) Details.
     *
     */
    public function testGetHDWalletXPubYPubZPubDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listHDWalletXPubYPubZPubTransactions
     *
     * List HD Wallet (xPub, yPub, zPub) Transactions.
     *
     */
    public function testListHDWalletXPubYPubZPubTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listHDWalletXPubYPubZPubUTXOs
     *
     * List HD Wallet (xPub, yPub, zPub) UTXOs.
     *
     */
    public function testListHDWalletXPubYPubZPubUTXOs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSyncedAddresses
     *
     * List Synced Addresses.
     *
     */
    public function testListSyncedAddresses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for prepareATransactionFromAnAddressInHDWalletXPubYPubZPub
     *
     * Prepare A Transaction From An Address In HD Wallet (xPub, yPub, zPub).
     *
     */
    public function testPrepareATransactionFromAnAddressInHDWalletXPubYPubZPub()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for prepareAUTXOBasedTransactionFromHDWalletXPubYPubZPub
     *
     * Prepare A UTXO-Based Transaction From HD Wallet (xPub, yPub, zPub).
     *
     */
    public function testPrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPub()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for syncHDWalletXPubYPubZPub
     *
     * Sync HD Wallet (xPub, yPub, zPub).
     *
     */
    public function testSyncHDWalletXPubYPubZPub()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for syncNewHDWalletXPubYPubZPub
     *
     * Sync New HD Wallet (xPub, yPub, zPub).
     *
     */
    public function testSyncNewHDWalletXPubYPubZPub()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
